-- CreateTable
CREATE TABLE "CaptionTemplate" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "isSeeded" BOOLEAN NOT NULL DEFAULT false,
    "fontName" TEXT NOT NULL DEFAULT 'DejaVu Sans',
    "fontColor" TEXT NOT NULL DEFAULT '#ffffff',
    "outlineColor" TEXT NOT NULL DEFAULT '#000000',
    "backColor" TEXT,
    "outlineWidth" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "shadow" BOOLEAN NOT NULL DEFAULT false,
    "shadowDepth" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "bold" BOOLEAN NOT NULL DEFAULT true,
    "italic" BOOLEAN NOT NULL DEFAULT false,
    "underline" BOOLEAN NOT NULL DEFAULT false,
    "alignment" INTEGER NOT NULL DEFAULT 2,
    "scaleX" DOUBLE PRECISION NOT NULL DEFAULT 100,
    "scaleY" DOUBLE PRECISION NOT NULL DEFAULT 100,
    "spacing" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "uppercase" BOOLEAN NOT NULL DEFAULT true,
    "borderStyle" INTEGER NOT NULL DEFAULT 1,
    "layouts" JSONB NOT NULL,
    "preview" JSONB NOT NULL,
    "hookOverrides" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CaptionTemplate_pkey" PRIMARY KEY ("id")
);

-- Seed default caption templates
INSERT INTO "CaptionTemplate" ("id","name","description","isSeeded","fontName","fontColor","outlineColor","outlineWidth","shadow","shadowDepth","bold","italic","underline","alignment","scaleX","scaleY","spacing","uppercase","borderStyle","layouts","preview","hookOverrides","createdAt","updatedAt")
VALUES
(
  'bold-yellow',
  'Bold Yellow',
  'Heavy sans-serif, centered, high contrast yellow',
  true,
  'DejaVu Sans',
  '#e2e469',
  '#000000',
  0.3,
  false,
  1,
  true,
  false,
  false,
  2,
  100,
  100,
  0,
  true,
  1,
  '{"portrait":{"fontSize":12,"maxWordsPerPhrase":2,"marginV":20,"marginL":70,"marginR":70,"previewFontSize":12},"square":{"fontSize":16,"maxWordsPerPhrase":3,"marginV":20,"marginL":55,"marginR":55,"previewFontSize":16},"landscape":{"fontSize":16,"maxWordsPerPhrase":4,"marginV":20,"marginL":45,"marginR":45,"previewFontSize":14}}',
  '{"fontFamily":"\"DejaVu Sans\", sans-serif","fontWeight":800,"textColor":"#e2e469","backgroundColor":"transparent","borderColor":"#000000","borderWidth":0.3,"textShadow":"none"}',
  '{"enabled":true,"fontSizeMultiplier":1.08,"position":"top","marginV":50}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'bold-center',
  'Bold Yellow (legacy)',
  'Legacy alias for bold-yellow',
  true,
  'DejaVu Sans',
  '#e2e469',
  '#000000',
  0.3,
  false,
  1,
  true,
  false,
  false,
  2,
  100,
  100,
  0,
  true,
  1,
  '{"portrait":{"fontSize":12,"maxWordsPerPhrase":2,"marginV":20,"marginL":70,"marginR":70,"previewFontSize":12},"square":{"fontSize":16,"maxWordsPerPhrase":3,"marginV":20,"marginL":55,"marginR":55,"previewFontSize":16},"landscape":{"fontSize":16,"maxWordsPerPhrase":4,"marginV":20,"marginL":45,"marginR":45,"previewFontSize":14}}',
  '{"fontFamily":"\"DejaVu Sans\", sans-serif","fontWeight":800,"textColor":"#e2e469","backgroundColor":"transparent","borderColor":"#000000","borderWidth":0.3,"textShadow":"none"}',
  '{"enabled":true,"fontSizeMultiplier":1.08,"position":"top","marginV":50}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'classic-white',
  'Classic White',
  'Bold white text with sharp black outline',
  true,
  'Montserrat',
  '#ffffff',
  '#000000',
  2,
  true,
  1,
  true,
  false,
  false,
  2,
  100,
  100,
  0,
  true,
  1,
  '{"portrait":{"fontSize":24,"maxWordsPerPhrase":2,"marginV":30,"marginL":60,"marginR":60,"previewFontSize":13},"square":{"fontSize":22,"maxWordsPerPhrase":3,"marginV":25,"marginL":50,"marginR":50,"previewFontSize":16},"landscape":{"fontSize":18,"maxWordsPerPhrase":4,"marginV":20,"marginL":40,"marginR":40,"previewFontSize":13}}',
  '{"fontFamily":"Montserrat, sans-serif","fontWeight":900,"textColor":"#ffffff","backgroundColor":"transparent","borderColor":"#000000","borderWidth":2,"textShadow":"2px 2px 4px rgba(0,0,0,0.9)"}',
  '{"enabled":true,"fontSizeMultiplier":1.08,"position":"top","marginV":50}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'neon-bebas',
  'Neon Pink',
  'Bright neon pink with yellow outline, Bebas Neue',
  true,
  'Bebas Neue',
  '#FF6B9D',
  '#FFD93D',
  1,
  false,
  1,
  false,
  false,
  false,
  2,
  100,
  110,
  0,
  true,
  1,
  '{"portrait":{"fontSize":28,"maxWordsPerPhrase":2,"marginV":25,"marginL":65,"marginR":65,"previewFontSize":14},"square":{"fontSize":26,"maxWordsPerPhrase":3,"marginV":25,"marginL":50,"marginR":50,"previewFontSize":17},"landscape":{"fontSize":22,"maxWordsPerPhrase":4,"marginV":20,"marginL":40,"marginR":40,"previewFontSize":14}}',
  '{"fontFamily":"\"Bebas Neue\", sans-serif","fontWeight":400,"textColor":"#FF6B9D","backgroundColor":"transparent","borderColor":"#FFD93D","borderWidth":1.5,"textShadow":"none"}',
  '{"enabled":true,"fontSizeMultiplier":1.1,"position":"top","marginV":50}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'mono-box',
  'Mono Box',
  'Yellow monospace text on dark background box',
  true,
  'DejaVu Sans Mono',
  '#FFD93D',
  '#000000',
  0,
  false,
  1,
  true,
  false,
  false,
  2,
  100,
  100,
  0,
  true,
  3,
  '{"portrait":{"fontSize":14,"maxWordsPerPhrase":2,"marginV":25,"marginL":60,"marginR":60,"previewFontSize":12},"square":{"fontSize":16,"maxWordsPerPhrase":3,"marginV":20,"marginL":50,"marginR":50,"previewFontSize":14},"landscape":{"fontSize":14,"maxWordsPerPhrase":4,"marginV":18,"marginL":40,"marginR":40,"previewFontSize":12}}',
  '{"fontFamily":"\"DejaVu Sans Mono\", monospace","fontWeight":700,"textColor":"#FFD93D","backgroundColor":"rgba(0,0,0,0.85)","borderColor":"#000000","borderWidth":0,"textShadow":"none"}',
  '{"enabled":true,"fontSizeMultiplier":1.08,"position":"top","marginV":50}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'minimal-inter',
  'Minimal Clean',
  'Light Inter text, subtle outline, professional',
  true,
  'Inter',
  '#F5F5F5',
  '#333333',
  0.5,
  false,
  1,
  false,
  false,
  false,
  2,
  100,
  100,
  0,
  false,
  1,
  '{"portrait":{"fontSize":20,"maxWordsPerPhrase":3,"marginV":30,"marginL":70,"marginR":70,"previewFontSize":12},"square":{"fontSize":18,"maxWordsPerPhrase":4,"marginV":25,"marginL":55,"marginR":55,"previewFontSize":14},"landscape":{"fontSize":16,"maxWordsPerPhrase":5,"marginV":20,"marginL":45,"marginR":45,"previewFontSize":12}}',
  '{"fontFamily":"Inter, sans-serif","fontWeight":400,"textColor":"#F5F5F5","backgroundColor":"transparent","borderColor":"#333333","borderWidth":0.5,"textShadow":"1px 1px 2px rgba(0,0,0,0.5)"}',
  '{"enabled":true,"fontSizeMultiplier":1.05,"position":"top","marginV":50}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("id") DO NOTHING;
